### ISSUE TITLE
incorrect opcode generated for cv.elw 

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-binutils-gdb#112]
shown on both 20231128 and 20231205 released cv toolchain.

Illegal instruction (core 0) at PC 0x1c5c0250:

1c5c0250:             03c9e003          cv.elw   zero,60(s3)

![image](https://github.com/openhwgroup/corev-binutils-gdb/assets/6898281/3cef7613-b796-4fde-9317-d3b383d48d01)

**Comment by MaryBennett** [comment]
Fix merged
