### ISSUE TITLE
Additional warning for clipr/clipur instructions

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#116]
clipr/clipur instructions description have been updated in cv32e40p_v1.7.0 User Manual/tag.
rs2 MSB is now masked and is not used by HW.

Maybe a warning should be printed in case rs2 MSB is at 1 to signal that it will not be used.

**Comment by jeremybennett** [comment]
I think this refers to `clip` and `clipu`.  For the register instructions, the assembler has no visibility of the register state.

**Comment by jeremybennett** [comment]
The assembler cannot see the state of rs2, so cannot issue any warning.  Marking as closed.
