### ISSUE TITLE
Error not generated for cv.shuffle.sci.h with wrong Imm6 value

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#117]
For cv.shuffle.sci.h Imm6[5:2] must be 0.

When it is not, this should generate an error.

**Comment by zhixiao-zhang** [comment]
I have created a PR #118 to fix this issue.

**Comment by jeremybennett** [comment]
> I have created a PR #118 to fix this issue.

@forceofsystem Thanks for your PR.  This was solved alternatively in commit 5507304cbdd

**Comment by jeremybennett** [comment]
Fixed in commit 5507304cbdd
