### ISSUE TITLE
Zc toolchain does not seem to allow half-word aligned functions

### ISSUE THREAD

**Issue by silabs-kjetil** [openhwgroup/corev-binutils-gdb#45]
When building code with the zc* extensions enabled I notice that functions are always word aligned and padding bytes are added which makes the code size larger than expected. Is this a bug in the binutils part of the toolchain, or somewhere else? Is there a way I can force the compiler to accept half-word aligned functions? I am using the following march and mabi arguments:

`-march=rv32ima_zca_zcb_zcmb_zcmp_zcmt -mabi=ilp32`

**Comment by simonpcook** [comment]
@jeremybennett, I believe this is the issue you were testing a fix for? Does it make sense to assign this one to yourself?

**Comment by jeremybennett** [comment]
Yes. Will you give a reply and note that I will pick it up

Thx, J

**Comment by silabs-kjetil** [comment]
Sounds good, glad you are picking this up @jeremybennett. Do you know if there is an easy way to patch my local toolchain to always allow half-word aligned functions temporarily as a workaround until the proper fix is in place?

**Comment by silabs-kjetil** [comment]
Looks like it was gcc that inserter alignment requirements, so I was able to force 16 bit function alignment by doing the following modification inside gcc/config/riscv/riscv.h as a temporary workaround.

```
//#define FUNCTION_BOUNDARY (TARGET_RVC ? 16 : 32)
#define FUNCTION_BOUNDARY (16)
```

**Comment by jeremybennett** [comment]
Hi @silabs-kjetil I'm just back from GNU Tools Cauldron and it sounds like you have already found the place to fix. We'll work on getting this fixed generically.

**Comment by pz9115** [comment]
I think I can fix it

**Comment by jeremybennett** [comment]
@pz9115 is going to provide the patch

**Comment by pz9115** [comment]
Updated with PR https://github.com/openhwgroup/corev-gcc/pull/11

**Comment by jeremybennett** [comment]
This was actually a GCC issue, which is now fixed.
