### ISSUE TITLE
Zcmp CFI may need fixing

### ISSUE THREAD

**Issue by abukharmeh** [openhwgroup/corev-binutils-gdb#47]
It looks like we used CFI information from msave restore to implement push/pop, while they are reversed ?
This could potentially mean that the debugger wont work when we have exception and we try to unwind stack frame
ref : https://github.com/riscv/riscv-code-size-reduction/issues/182

**Comment by linsinan1995** [comment]
The current CFI info is correct. The mentioned problem is the order of CFI, or the order of saving/restoring is different from the example in spec.

I don't think we need to make any change unless the spec has a regulation for the order of saving.

**Comment by abukharmeh** [comment]
So you think the offsets are correct ? (I.e I dont think there is restriction on what order the stores are, but their location in memory) If so we can close this issue.

**Comment by linsinan1995** [comment]
Better double-check it. But the implementation of the push/pop order also follows the implementation of msave-restore, and that is why they have the same CFI order.

**Comment by jeremybennett** [comment]
This is actually a GCC problem see [GCC issue #20](https://github.com/openhwgroup/corev-gcc/issues/20)

**Comment by jeremybennett** [comment]
Closing issue, now it is filed with GCC
