### ISSUE TITLE
Immediate encoding not correct for 8/16-b SIMD instructions

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#53]
Hi,

Like in RISC-V specification (JAL example) , all PULP instructions are described using following notation for immediate:

immx[0|x-1:1] means for a decimal value encoded on x bits, bit 0 comes first and then (x-1):1

For instance:
24 =0x18 => imm6[5:0] = 0b01_1000 so imm6[0|5:1] = 0b00_1100

Right now assembler is using imm6[5:0] rather than imm6[0|5:1] in binary encoding of PULP instructions.

Cheers,
Pascal.

**Comment by jeremybennett** [comment]
@pascalgouedo thanks for this. I will get @NandniJamnadas to fix this.

**Comment by NandniJamnadas** [comment]
@pascalgouedo I have a fix for this. I will submit a pull request as soon I finish testing.

**Comment by NandniJamnadas** [comment]
@pascalgouedo Here is the PR for this fix: https://github.com/openhwgroup/corev-binutils-gdb/pull/54

**Comment by jeremybennett** [comment]
Resolved in commit [60994899cc8aeaa6a96c3abb8230682e5a8e3de2](https://github.com/openhwgroup/corev-binutils-gdb/commit/60994899cc8aeaa6a96c3abb8230682e5a8e3de2)
