### ISSUE TITLE
cv.elw encoding not correct

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#57]
cv.elw is generated using v1 encoding:

> 01cfef83  cv.elw  x31,28(x31)

while it should be

> 01cfbf8b  cv.elw  x31,28(x31)

v2 specification extract:

> +-------------+--------+----------+--------+------------+---------------------------+
> | 31   :   20      | 19 :15  | 14  : 12    | 11 :07   | 06  :   00    |                                         |
> +-------------+--------+----------+--------+------------+---------------------------+
> | imm[11:0]    | rs1        | funct3     | rd         | opcode      | Mnemonic                       |
> +=======+=====+======+=====+=======+================+
> | offset           | base     | 011          | dest      | 000 1011   | **cv.elw rD, Imm(rs1)**   |
> +-------------+--------+----------+--------+------------+---------------------------+

**Comment by NandniJamnadas** [comment]
Hi @pascalgouedo here is the PR to this fix: https://github.com/openhwgroup/corev-binutils-gdb/pull/58

**Comment by jeremybennett** [comment]
Now resolved by #58
