### ISSUE TITLE
the encoding of cv.starti may need to be updated

### ISSUE THREAD

**Issue by ChunyuLiao** [openhwgroup/corev-binutils-gdb#63]
[ 	]+4:[ 	]+5e6040ab[ 	]+cv.starti[ 	]+1,bd0 +<target\+0xbd0>

https://github.com/openhwgroup/corev-binutils-gdb/blob/development/gas/testsuite/gas/riscv/cv-hwlp-starti.d#L11

the new spec: https://github.com/openhwgroup/cv32e40p/blob/master/docs/source/instruction_set_extensions.rst

| 31   :   20           | 19 :15       | 14  : 12 | 11 :08  | 07 | 06  :   00  |                                              |

| uimmL[11:0]     | 00000      | 100       | 0000   | L   | 010 1011   | **cv.starti L, uimmL**        |

According to the new spec, the **cv.starti 1,bd0** seems to be  bd, 00,  40, ab, not 5e, 60, 40, ab?

**Comment by jeremybennett** [comment]
This is now resolved by #70.
