### ISSUE TITLE
[CV32E40Pv2] Compiler error for cv.minu/maxu.sci.*

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#66]
For all cv.min/maxu.sci.* instructions, immediate values should be treated as unsigned as stated in the specification:

`3. Immediate scalar replication mode (.sci), vector-scalar operation.
   Operand 1 is treated as vector, while operand 2 is treated as a
   scalar and comes from an immediate. The immediate is either sign- or
   zero-extended, depending on the operation. If not specified, the
   immediate is sign-extended.`
   
But the compiler is giving an error:

`Error: immediate value must be 6-bit signed, 50 is out of range`

**Comment by NandniJamnadas** [comment]
There is a pull request for this fix: [CV32E40Pv2 SIMD 6-bit Unsigned Immediate + Updated SIMD instructions from signed to unsigned](https://github.com/openhwgroup/corev-binutils-gdb/pull/74), @pascalgouedo could you please check if the correct instructions listed use a 6-bit unsigned immediate.

**Comment by jeremybennett** [comment]
This should be resolved by https://github.com/openhwgroup/corev-binutils-gdb/pull/74
