### ISSUE TITLE
[CV32E40Pv2] Compiler error for cv.shuffleI*.sci.*

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#67]
For all cv.shuffleI*.sci.* instructions, the specification is maybe not clear enough but immediate values should always be treated as unsigned. Because this immediate value is not representing a number (its sub-parts are individually used as indexes).

Specification will be improved for that point.

**Comment by NandniJamnadas** [comment]
There is a pull request for this fix: [CV32E40Pv2 SIMD 6-bit Unsigned Immediate + Updated SIMD instructions from signed to unsigned](https://github.com/openhwgroup/corev-binutils-gdb/pull/74), @pascalgouedo could you please check if the correct instructions listed use a 6-bit unsigned immediate.

**Comment by jeremybennett** [comment]
This should be resolved by https://github.com/openhwgroup/corev-binutils-gdb/pull/74.
