### ISSUE TITLE
[CV32E40Pv2] Bit Manipulation instructions

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#68]
The encoding is incorrect for all Bit Manipulation instructions. Is2 and Is3 are interchanged in final bit encoding.
Maybe because they are declared differently than other instructions : ... rD, rs1, Is3, Is2

This different instruction presentation is because this is easier to understand what is extracted:
Is3 is most significant bit and Is2 is least significant bit.

**Comment by jeremybennett** [comment]
Fixed by https://github.com/openhwgroup/corev-binutils-gdb/pull/71
