### ISSUE TITLE
[CV32E40Pv2] Some multiplication instructions not existing anymore

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#69]
Hi,

During the PULP instructions re-encoding, it appeared that some instructions were redundant and have been removed.

They are cv.mulu, cv.muls, cv.mulhhu and cv.mulhhs.

Toolchain should generate an error when trying to use them or
assembler pseudo-instruction should be added to emulate them (cv.mul* ... => cv.mul*N ... , 0).

**Comment by NandniJamnadas** [comment]
@pascalgouedo I think it's best we implement puesdo-instructions for these four instructions. The assembler will already generate an error if you try and use the four instructions above. Also implementing four puesdo-instruction is much easier than adding a custom error message for the specific instructions.

**Comment by pascalgouedo** [comment]
Hi @NandniJamnadas 

Pseudo-instructions is my preferred solution as well.

**Comment by NandniJamnadas** [comment]
This issue is now fixed with pull request [#92](https://github.com/openhwgroup/corev-binutils-gdb/pull/92) CV32E40Pv2 MAC pseudo-instructions.
