### ISSUE TITLE
Does Event Load Word need a custom relocation

### ISSUE THREAD

**Issue by jeremybennett** [openhwgroup/corev-binutils-gdb#79]
The question of relocation has not been addressed for the Event Load Word instruction.  Does it need a custom relocation?

**Comment by linsinan1995** [comment]
I don't see any difference between elw and lw in terms of the linker process, so no relocation is needed for elw. Anything I missed?

**Comment by simonpcook** [comment]
No, I don't think anything was missed here. This question was left over from a discussion about what custom relocations were needed, but had not yet been closed.

@jeremybennett Could you close this next time you go through the issue list?

**Comment by jeremybennett** [comment]
Thanks @simonpcook @linsinan1995. I will close the issue.
