### ISSUE TITLE
Incorrectly compiles functions in newlib with Zcmt-ext

### ISSUE THREAD

**Issue by muxiff** [openhwgroup/corev-binutils-gdb#82]
hi,    
        When I used the toolchain that enabled zcmt extension to compile the executable program using newlib, I found that the `_localeconv_r` was compiled into redundant `cm.jalt` instructions, which caused the program to enter a dead loop. That was inconsistent with the actual behavior of the function. 

The test cases are as follows:  
- enable Zcmt:  

 ` 80002fe4 <_localeconv_r>:`
 `80002fe4:	0fffd517          	  auipc	a0,0xfffd`
 `80002fe8:	a17a                	cm.jalt	94 # 80002fe4 <_sp+0xefff2fe4>`
 `80002fea:	16c0                	addi	s0,sp,868`
 `80002fec:	8082                	ret  `

- disable Zcmt:  

 `80004088 <_localeconv_r>:`
 `80004088:	0fffc517          	auipc	a0,0xfffc`
 `8000408c:	0c850513          	addi	a0,a0,200 # 90000150 <__global_locale+0xf0>`
 `80004090:	00008067          	ret`

**Comment by linsinan1995** [comment]
thanks for the feedback. I can reproduce this bug when compiling corev-toolchain with cmodel=medany.

Updates:
when replacing instructions with table jump instructions, the linker used to only do a search based on the symbol address, which is incorrect if the relocation is not R_RISCV_CALL[PLT]/R_RISCV_JAL. I opened a PR to fix it.

**Comment by NandniJamnadas** [comment]
This issue has been fixed by pull request [#83](https://github.com/openhwgroup/corev-binutils-gdb/pull/83).
