### ISSUE TITLE
Using hexadecimal value for instruction signed immediate seems restricted to positive values.

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#85]
Hi,

Using following standard RISC-V bit manipulation instruction with hexadecimal value (for immediate) having 6th bit set to one to have sign-extension is giving an error from assembler:
 
   c.andi x8, 0x3c

  test.S: Assembler messages:
  test.S:247: Error: illegal operands `c.andi x8,0x3c'

while c.andi x8, 0x1c is not having error.

Only way to achieve required final mask (0xffff_fffc) without error is to use decimal value for immediate:
  c.andi x8, -4

I know this is the **preferred** way for disassembler to print short immediate using decimal representation.
But I was expecting assembler would accept both hexadecimal/decimal representation as it is weird to use decimal values for masks in bit manipulation instructions.

**Comment by pascalgouedo** [comment]
Just tried and using 32 bit hexadecimal value gives the same error.
Error: illegal operands `c.andi x7,0xfffffffc'

Same for 16-b and 8-bit values (0xfffc and 0xfc).

Only -4 works ☹

**Comment by jeremybennett** [comment]
This appears to be a limitation in the generic RISC-V assembler parser.  However I don't believe we can fix this in a way that will be acceptable upstream, because of the risk of breaking existing code.
