### ISSUE TITLE
Post-Increment Register-Immediate Load should be updated

### ISSUE THREAD

**Issue by ChunyuLiao** [openhwgroup/corev-binutils-gdb#87]
https://github.com/openhwgroup/corev-binutils-gdb/blob/development/gas/testsuite/gas/riscv/cv-mem-lb.s
	cv.lb t0, -2048(t2)
	cv.lb t4, 15(t1)
	cv.lb t3, 2047(t5)

these instructions should be updated to:
	cv.lb t0, -2048(t2!)
	cv.lb t4, 15(t1!)
	cv.lb t3, 2047(t5!)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/26795311/236361842-7ac0552a-98bc-4f2c-a0d4-19a48c5f7633.png">

**Comment by NandniJamnadas** [comment]
This is a mistake in the GNU assembler and in the testing. We have accidentally defined `cv.lb rd, imm(rs)` as a synonym of standard RISC-V `lb`. The same appears for all the other CORE-V loads and stores. We will remove this and update the tests.

**Comment by NandniJamnadas** [comment]
This issue is now fixed with pull request [#90](https://github.com/openhwgroup/corev-binutils-gdb/pull/90) CV32E40Pv2 Update Post Increment Load/Store.
