### ISSUE TITLE
The immediate field of shift instructions should be unsigned

### ISSUE THREAD

**Issue by melonedo** [openhwgroup/corev-binutils-gdb#89]
Raised from https://github.com/openhwgroup/corev-llvm-project/pull/48#issuecomment-1491547442.
This can be confirmed that in [cv-simd-srl-sci-b-pass.s](https://github.com/openhwgroup/corev-binutils-gdb/blob/19bb59dcc50028891e437245e0e7000428976349/gas/testsuite/gas/riscv/cv-simd-srl-sci-b-pass.s), tests assume negative shift amount, which should be unsigned:

https://github.com/openhwgroup/corev-binutils-gdb/blob/19bb59dcc50028891e437245e0e7000428976349/gas/testsuite/gas/riscv/cv-simd-srl-sci-b-pass.s#L10

**Comment by NandniJamnadas** [comment]
This issue is now fixed with pull request https://github.com/openhwgroup/corev-binutils-gdb/pull/91 CV32E40Pv2 Update SIMD Instructions and Tests.
