### ISSUE TITLE
disassembler translate cv.insert machine code wrongly to cv.muls

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-binutils-gdb#93]
Toolchain version:

corev-openhw-gcc-centos7-20230504

Problem Statement:

In the generated dump file.

PC                    instruction
1c02442a:	810707db          	cv.muls	a5,a4,a6

as per CV manual below, the opcode of the instruction is 1011011, which matches with cv.insert instead of cv.muls.

<html>
<body>

10|Luimm5[4:0] | Iuimm5[4:0] | src | 000 | dest | 101 1011 | cv.insert rD, rs1, Is3, Is2
-- |-- | -- | -- | -- | -- | -- | --

</body>
</html>

**Comment by jeremybennett** [comment]
Thanks @superflyers This looks to be a bug. I am guessing a mistake in the disassembly decoding tables. Since @NandniJamnadas is on vacation, I have also assigned to @MaryBennett to investigage.

**Comment by MaryBennett** [comment]
@NandniJamnadas's commit changing cv.muls into a pseudo instruction has fixed this. It is currently only in upstream. There will be new binaries coming out in a couple of weeks.

**Comment by NandniJamnadas** [comment]
This issue has been fixed under PR: [#92](https://github.com/openhwgroup/corev-binutils-gdb/pull/92) CV32E40Pv2 MAC pseudo-instructions.
